repos:
    - repo: local
      hooks:
          - id: swiftlint-lint
            name: swiftlint
            entry: Scripts/swiftlint.sh
            language: script
            types: [swift]
          - id: swiftlint-lint-fix
            name: swiftlint lint --fix
            entry: Scripts/swiftlint-fix.sh
            language: script
            types: [swift]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          # - id: check-shebang-scripts-are-executable
