steps:
    - command:
          - swift build
    - command:
          - cd Demo
          - xcodebuild -scheme 'RenderKitDemo' -allowProvisioningUpdates -destination 'generic/platform=macOS'
    - command:
          - cd Demo
          - xcodebuild -scheme 'RenderKitDemo' -allowProvisioningUpdates -destination 'generic/platform=iOS'
