#!/usr/bin/env python3

from pathlib import Path
import re
import shlex
import subprocess
import sys

### Check for iCloud "bad" filenames
output: bytes = subprocess.check_output(shlex.split("git diff --cached --name-only"))
paths = [
    Path(line) for line in output.decode("utf-8").splitlines(keepends=False)
]
for path in paths:
    # print(f'Checking \"{path.stem}\"', file=sys.stderr)
    if re.match(r"^.+ ([2-9]\d*)$", path.stem):
        print(f"error: {path} is not a valid name", file=sys.stderr)
        sys.exit(1)

### Check git user email address.
output: bytes = subprocess.check_output(shlex.split("git config user.email"))
if output.decode("utf-8").strip() != "jwight@mac.com":
    print(f"error: Invalid user.email address", file=sys.stderr)
    sys.exit(1)
