name: Swift
env:
    XCODE_SCHEME: "RenderKitDemos"
    XCODE_PROJECT_PATH: "./Demos"
    XCODE_VERSION: "latest-stable"
on:
  push:
  pull_request:
jobs:
  swift-build:
    runs-on: macos-15 # macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@v3
      - run: swift build -v
      - run: swift test -v
  xcode-build:
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 16 Plus", "generic/platform=iOS", "generic/platform=macOS"]
    runs-on: macos-15 # macos-latest
    steps:
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: ${{ env.XCODE_VERSION }}
        - uses: actions/checkout@v3
        - run: xcodebuild -scheme "${{ env.XCODE_SCHEME }}" -destination "${{ matrix.destination }}" build CODE_SIGNING_ALLOWED=NO
          working-directory: "${{ env.XCODE_PROJECT_PATH }}"
